name: Security_Catalog Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.7

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan
          echo "Terraform Plan Output:"
          terraform show -json tfplan | tee tfplan_output.json

      - name: Validate Terraform Plan Output
        run: |
          echo "Validating JSON output..."
          cat tfplan_output.json | jq . || { echo "JSON validation failed"; exit 1; }

      - name: Apply Terraform Plan
        if: success()
        run: terraform apply -auto-approve tfplan

      - name: Clean up
        if: always()
        run: terraform destroy -auto-approve || echo "Destroy step failed."
